name: Release ALL

on:
  workflow_dispatch:

jobs:
  build-mac-release:
    runs-on: macos-11
    strategy:
      matrix:
        arch:
          - x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}
      - run: |
            git submodule update --init --recursive
            git submodule foreach "git submodule update --init"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/kcp_*
        
      - run: zip -j ${{ matrix.arch }} ./target/${{ matrix.arch }}/release/kcp_*
    
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            files: |
                ${{ matrix.arch }}.zip

  build-windows-release:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86_64-pc-windows-msvc        
          - i686-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}
      - run: |
          git submodule update --init --recursive
          git submodule foreach "git submodule update --init"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/kcp_*
        
      - run: ./zip/zip.exe -j ${{ matrix.arch }} ./target/${{ matrix.arch }}/release/kcp_*
    
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            files: |
                ${{ matrix.arch }}.zip

  build-linux-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-musl
          - mips-unknown-linux-musl
          - mips-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - aarch64-linux-android
          - i686-linux-android
          - x86_64-linux-android
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          git submodule update --init --recursive
          git submodule foreach "git submodule update --init"
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: cross build --release --target ${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/kcp_*
      
      - run: zip -j ${{ matrix.arch }} ./target/${{ matrix.arch }}/release/kcp_*

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            files: |
                ${{ matrix.arch }}.zip